apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: mrud-inpatient-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: mrud-inpatient-webapi-config
    literals:
      - database=mrud-inpatient
      - collection=inpatient
patches:
 - path: patches/webapi.deployment.yaml
   target:
     group: apps
     version: v1
     kind: Deployment
     name: mrud-inpatient-webapi